### PR TITLE
Allow passing `smat` kwarg through `nblast_allbyall`

### PR DESCRIPTION
**Pull request by bdpedigo**
Hi @schlegelp - I was hoping to allow passing the `smat` kwarg to `NBlaster` through the `nblast_allbyall` function.

Note: I saw #28 so let me know if there are any collisions there (possibly just the parameter would need to be copied over description it looked like). 

Let me know if this looks okay or if there's anything you'd want me to revise.

### CODE REVIEW

**Comment by schlegelp** [comment]
Hi @bdpedigo! That looks good to me and I really should have exposed that parameter for pass-through from the get-go. As you pointed out, #28 will likely introduce some changes to scoring functions - quite possibly including renaming that parameter. 

With that disclaimer: I think @clbarnes is still tinkering around with #28 (and clearly has a some good ideas for further improvement!) and while that is I'm happy to merge your PR. @clbarnes that won't cause any issues for you, will it?

I _might_ have suggested that you also add `smat` parameters to `nblast()`, `nblast_smart()` and to `synblast()` to make things consistent?

**Comment by clbarnes** [comment]
I'm happy for this change to go in in the mean time (with the same changes to the other functions), #28 should rebase cleanly.

**Comment by bdpedigo** [comment]
sure, I'll add to those other functions as well

**Comment by bdpedigo** [comment]
should be taken care of

**Comment by schlegelp** [comment]
Thanks for the contribution Ben!

**Comment by bdpedigo** [comment]
thank you @clbarnes & @schlegelp, Navis/pymaid have been super useful for me!

**Comment by schlegelp** [comment]
FYI: I just released a new version of navis. So unless you desperately need it, it might be a while before your addition makes it to PyPI?

**Comment by bdpedigo** [comment]
no worries, I'm running a local copy at the moment so I'll be fine

**Comment by clbarnes** [comment]
You can also install directly from github (useful if you're keep track of your dependencies in a `requirements.txt`); `pip install git+https://github.com/schlegelp/navis.git`, append `@r3v1si0n` for a particular branch, tag, or commit.

**Pull request merged**
